version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '9889:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=newsblog
        ports:
            - '9892:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9888:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
